2018-05-06 13:26:13,453 [Thread-2:140362118285056] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 21, in index
    return render(request, 'blog/index.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    with context.bind_template(self):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/context.py", line 235, in bind_template
    updates.update(processor(self.request))
TypeError: global_setting() takes no arguments (1 given)
2018-05-07 01:23:41,792 [Thread-3:139949931042560] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-05-07 01:39:47,790 [Thread-9:139978466948864] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1467, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1078, in save_model
    obj.save()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1048, "Column 'user_id' cannot be null")
2018-05-07 02:37:00,036 [Thread-3:139842206693120] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-05-07 04:12:15,993 [Thread-2:140202628396800] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 21, in index
    return render(request, 'blog/index.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 146, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2018-05-07 04:14:42,372 [Thread-2:139967501174528] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 21, in index
    return render(request, 'blog/index.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 146, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2018-05-07 04:15:33,748 [Thread-7:139967263135488] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 21, in index
    return render(request, 'blog/index.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 146, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2018-05-07 04:16:47,257 [Thread-13:139967279920896] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-05-07 04:16:47,262 [Thread-12:139967271528192] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-05-07 04:16:47,265 [Thread-15:139967263135488] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-05-07 04:16:47,280 [Thread-14:139967492781824] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-05-07 04:17:44,794 [Thread-3:139996764747520] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-05-07 04:17:44,803 [Thread-5:139996764747520] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-05-07 04:17:44,808 [Thread-4:139996756354816] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-05-07 04:17:44,814 [Thread-6:139996773140224] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-05-07 04:25:47,572 [Thread-17:139996539385600] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 21, in index
    return render(request, 'blog/index.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'static', expected 'endblock'
2018-05-07 04:27:14,065 [Thread-20:139996539385600] [django.request:170] [base:get_response] [WARNING]- Not Found: /src="/static/images/a2.jpg"
2018-05-07 04:27:14,068 [Thread-21:139996756354816] [django.request:170] [base:get_response] [WARNING]- Not Found: /src="/static/images/a3.jpg"
2018-05-07 04:27:14,073 [Thread-22:139996764747520] [django.request:170] [base:get_response] [WARNING]- Not Found: /src="/static/images/a4.jpg"
2018-05-07 04:28:18,018 [Thread-24:139996756354816] [django.request:170] [base:get_response] [WARNING]- Not Found: /src="/static/images/a1.jpg"
2018-05-07 04:28:18,021 [Thread-25:139996539385600] [django.request:170] [base:get_response] [WARNING]- Not Found: /src="/static/images/a3.jpg"
2018-05-07 04:28:18,027 [Thread-26:139996539385600] [django.request:170] [base:get_response] [WARNING]- Not Found: /src="/static/images/a4.jpg"
2018-05-07 07:39:41,459 [Thread-12:140651454789376] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.html
2018-05-07 07:39:44,635 [Thread-13:140651454789376] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.html
2018-05-07 07:57:25,392 [Thread-158:140651811120896] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-05-07 08:27:47,489 [Thread-85:140146125043456] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.html
2018-05-07 08:57:33,116 [Thread-7:140086174992128] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 34, in index
    return render(request, 'blog/index.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'category' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2018-05-07 09:01:47,860 [Thread-13:140085794174720] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 34, in index
    return render(request, 'blog/index.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'category' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2018-05-07 09:08:22,257 [Thread-2:140197944571648] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 34, in index
    return render(request, 'blog/index.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'category' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2018-05-07 09:08:22,769 [Thread-3:140197944571648] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-05-07 09:20:20,357 [Thread-90:140197857584896] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-05-07 18:01:36,522 [Thread-2:139764104156928] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/python/PycharmProjects/blog_project/blog_project/urls.py", line 28, in <module>
    url(r'^', include('blog.urls'))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/python/PycharmProjects/blog_project/blog/urls.py", line 7, in <module>
    url(r'^base/$', views.base, name='base'),
AttributeError: 'module' object has no attribute 'base'
2018-05-07 18:04:00,363 [Thread-2:140396071347968] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/python/PycharmProjects/blog_project/blog_project/urls.py", line 28, in <module>
    url(r'^', include('blog.urls'))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/python/PycharmProjects/blog_project/blog/urls.py", line 7, in <module>
    url(r'^base/$', views.base, name='base'),
AttributeError: 'module' object has no attribute 'base'
2018-05-07 18:04:38,318 [Thread-3:140396071347968] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/python/PycharmProjects/blog_project/blog_project/urls.py", line 28, in <module>
    url(r'^', include('blog.urls'))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/python/PycharmProjects/blog_project/blog/urls.py", line 7, in <module>
    url(r'^base/$', views.base, name='base'),
AttributeError: 'module' object has no attribute 'base'
2018-05-07 20:13:27,238 [Thread-3:140465935210240] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-05-07 20:13:35,427 [Thread-27:140465563236096] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-05-08 10:30:01,917 [Thread-25:140166383527680] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-05-08 10:52:48,338 [Thread-32:140244463515392] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 37, in index
    return render(request, 'blog/index.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 146, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: pagination.html
2018-05-08 10:53:15,033 [Thread-57:140244463515392] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 37, in index
    return render(request, 'blog/index.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 146, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: pagination.html
2018-05-08 13:31:16,215 [Thread-50:140693366585088] [django.request:170] [base:get_response] [WARNING]- Not Found: /article/
2018-05-08 13:31:20,351 [Thread-51:140693366585088] [django.request:170] [base:get_response] [WARNING]- Not Found: /article
2018-05-08 13:32:46,414 [Thread-3:140564146157312] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: article.html
2018-05-08 13:33:50,698 [Thread-4:139737364952832] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'myfilter' is not a valid tag library: Template library myfilter not found, tried django.templatetags.myfilter,django.contrib.admin.templatetags.myfilter,django.contrib.staticfiles.templatetags.myfilter
2018-05-08 13:36:52,132 [Thread-32:139737348167424] [django.request:170] [base:get_response] [WARNING]- Not Found: /article/id=1
2018-05-08 13:36:57,163 [Thread-33:139737348167424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'month_to_upper'
2018-05-08 13:48:15,415 [Thread-34:139737348167424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'myfilter' is not a valid tag library: Template library myfilter not found, tried django.templatetags.myfilter,django.contrib.admin.templatetags.myfilter,django.contrib.staticfiles.templatetags.myfilter
2018-05-08 13:48:51,999 [Thread-35:139737348167424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'blog.myfilter' is not a valid tag library: Template library blog.myfilter not found, tried django.templatetags.blog.myfilter,django.contrib.admin.templatetags.blog.myfilter,django.contrib.staticfiles.templatetags.blog.myfilter
2018-05-08 13:48:53,260 [Thread-36:139737348167424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'blog.myfilter' is not a valid tag library: Template library blog.myfilter not found, tried django.templatetags.blog.myfilter,django.contrib.admin.templatetags.blog.myfilter,django.contrib.staticfiles.templatetags.blog.myfilter
2018-05-08 13:49:52,062 [Thread-37:139737348167424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'django.templatetags.blog.myfilter' is not a valid tag library: Template library django.templatetags.blog.myfilter not found, tried django.templatetags.django.templatetags.blog.myfilter,django.contrib.admin.templatetags.django.templatetags.blog.myfilter,django.contrib.staticfiles.templatetags.django.templatetags.blog.myfilter
2018-05-08 13:49:53,123 [Thread-38:139737348167424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'django.templatetags.blog.myfilter' is not a valid tag library: Template library django.templatetags.blog.myfilter not found, tried django.templatetags.django.templatetags.blog.myfilter,django.contrib.admin.templatetags.django.templatetags.blog.myfilter,django.contrib.staticfiles.templatetags.django.templatetags.blog.myfilter
2018-05-08 13:52:28,066 [Thread-39:139737348167424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'django.templatetags.blog.myfilter' is not a valid tag library: Template library django.templatetags.blog.myfilter not found, tried django.templatetags.django.templatetags.blog.myfilter,django.contrib.admin.templatetags.django.templatetags.blog.myfilter,django.contrib.staticfiles.templatetags.django.templatetags.blog.myfilter
2018-05-08 13:52:56,994 [Thread-40:139737348167424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'myfilter' is not a valid tag library: Template library myfilter not found, tried django.templatetags.myfilter,django.contrib.admin.templatetags.myfilter,django.contrib.staticfiles.templatetags.myfilter
2018-05-08 13:59:24,874 [Thread-41:139737348167424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'myfilter' is not a valid tag library: Template library myfilter not found, tried django.templatetags.myfilter,django.contrib.admin.templatetags.myfilter,django.contrib.staticfiles.templatetags.myfilter
2018-05-08 14:00:58,750 [Thread-70:139737348167424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'myfilter' is not a valid tag library: Template library myfilter not found, tried django.templatetags.myfilter,django.contrib.admin.templatetags.myfilter,django.contrib.staticfiles.templatetags.myfilter
2018-05-08 14:08:10,475 [Thread-2:140019809281792] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'logout' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2018-05-08 14:08:32,937 [Thread-4:140019809281792] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 98, in article
    return render(request, 'blog/article.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'logout' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2018-05-08 14:11:49,316 [Thread-2:139907848304384] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/python/PycharmProjects/blog_project/blog_project/urls.py", line 14, in <module>
    url(r'^', include('blog.urls'))
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/python/PycharmProjects/blog_project/blog/urls.py", line 13, in <module>
    url(r'^category/$', views.category, name='category'),
AttributeError: 'module' object has no attribute 'category'
2018-05-08 14:15:47,592 [Thread-23:139861538961152] [django.request:170] [base:get_response] [WARNING]- Not Found: /article/index.html
2018-05-08 14:15:50,280 [Thread-24:139861538961152] [django.request:170] [base:get_response] [WARNING]- Not Found: /article/index.html
2018-05-08 14:15:55,594 [Thread-25:139861538961152] [django.request:170] [base:get_response] [WARNING]- Not Found: /article/index.html
2018-05-08 15:40:06,405 [Thread-103:139861573580544] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /reg
Traceback (most recent call last):
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/PycharmProjects/blog_project/blog/views.py", line 154, in do_reg
    return render(request, 'reg.html', locals())
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/python/.virtualenvs/blog-django/local/lib/python2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: reg.html
2018-05-08 16:59:07,471 [Thread-122:140236243855104] [django.request:170] [base:get_response] [WARNING]- Not Found: /article/index.html
2018-05-08 16:59:17,323 [Thread-124:140236243855104] [django.request:170] [base:get_response] [WARNING]- Not Found: /article/index.html
